# Generated by Django 2.2.5 on 2020-02-11 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200210_1230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewUser',
        ),
    ]
