# Generated by Django 2.2.5 on 2020-03-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0005_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile_pic',
            old_name='AP2Name',
            new_name='Priest_Name',
        ),
        migrations.RemoveField(
            model_name='profile_pic',
            name='APName',
        ),
        migrations.RemoveField(
            model_name='profile_pic',
            name='AsstPriest2_pic',
        ),
        migrations.RemoveField(
            model_name='profile_pic',
            name='AsstPriest_pic',
        ),
        migrations.RemoveField(
            model_name='profile_pic',
            name='PPName',
        ),
        migrations.AddField(
            model_name='profile_pic',
            name='Description',
            field=models.TextField(blank=True),
        ),
    ]
