# Generated by Django 2.2.5 on 2020-03-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0006_auto_20200302_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_pic',
            name='AsstPriest2_pic',
            field=models.ImageField(blank=True, upload_to='profile2'),
        ),
        migrations.AddField(
            model_name='profile_pic',
            name='AsstPriest_pic',
            field=models.ImageField(blank=True, upload_to='profile1'),
        ),
        migrations.AddField(
            model_name='profile_pic',
            name='Description2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile_pic',
            name='Description3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile_pic',
            name='Priest2_Name',
            field=models.CharField(blank=True, max_length=246),
        ),
        migrations.AddField(
            model_name='profile_pic',
            name='Priest3_Name',
            field=models.CharField(blank=True, max_length=246),
        ),
        migrations.AlterField(
            model_name='profile_pic',
            name='Priest_Name',
            field=models.CharField(blank=True, max_length=246),
        ),
    ]
