# Generated by Django 2.2.5 on 2020-03-03 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0007_auto_20200302_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_pic',
            name='AsstPriest2_pic',
        ),
        migrations.RemoveField(
            model_name='profile_pic',
            name='AsstPriest_pic',
        ),
        migrations.RemoveField(
            model_name='profile_pic',
            name='Description2',
        ),
        migrations.RemoveField(
            model_name='profile_pic',
            name='Description3',
        ),
        migrations.RemoveField(
            model_name='profile_pic',
            name='Priest2_Name',
        ),
        migrations.RemoveField(
            model_name='profile_pic',
            name='Priest3_Name',
        ),
    ]
