# Generated by Django 2.2.5 on 2020-03-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0008_auto_20200303_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='notices')),
            ],
            options={
                'db_table': 'notices',
            },
        ),
    ]
