# Generated by Django 2.2.5 on 2020-03-03 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0009_notices'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notices',
            table=None,
        ),
    ]
