# Generated by Django 2.2.5 on 2020-03-10 21:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0010_auto_20200303_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='notices',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
